// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbrxpnahfyoamolvioak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icnhwbmFoZnlvYW1vbHZpb2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODQzNTMsImV4cCI6MjA2MTg2MDM1M30.hGl4fwhv_djVIrXpAdpK2Zja6Origx4oiCz5o1fgOsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);